### ISSUE TITLE
appSettings.config & connectionStrings.config

### ISSUE THREAD

**Issue by waqasghouri89** [shockzinfinity/sapHowmuch.WebAPI#1]
Can you please add a dummy appSettings.config & connectionStrings.config with some random values, 
So anyone can change values accordingly. 

You can add the file manually that would really helps for others. :-)

**Comment by waqasghouri89** [comment]
Sample = > appSettings.config

```
<?xml version="1.0"?>
<appSettings>
  <add key="appEnvironment" value="prod" />
  <add key="sapServer" value="" />
  <add key="sapDbUsername" value="sa" />
  <add key="sapDbPassword" value="xxxxx" />
  <add key="sapCompanyDb" value="TEST_SANDBOX_SAP" />
  <add key="sapDbType" value="dst_MSSQL2016" />
  <add key="sapCompanyUser" value="manager" />
  <add key="sapCompanyPassword" value="XXXX" />
  <add key="isTrusted" value="false" />
  <add key="sapLicenseServer" value="" />
</appSettings>
```


Sample of connectionStrings.config
```

<?xml version="1.0"?>
<connectionStrings>
</connectionStrings>
```

**Comment by shockzinfinity** [comment]
[Yes, you're right.
But I didn't look into this repository because I'm not paying attention to it anymore. (Actually, I didn't think anyone would be interested in this repository. :-))
Anyway, thank you for your advice.

I'm uploading a sample after adding it.

Thank you for your feedback. @waqasghouri89
